app:
  build: .
  command: bin/rails server -p 3000 -b 0.0.0.0
  ports:
    - "3000:3000"
  volumes:
   - .:/srv/app
   - ./log:/srv/app/log
  links:
    - postgres

postgres:
  image: iamliamnorton/postgres
  ports:
    - "5432"
