# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb76e2dd5902665ab929bc357262e6aa2a0048220f76f20613b1c1560567a088a7d5a8e4770d2cf98d9d90c11fad70c799fcbe73393c80566ae27b185e34074

test:
  secret_key_base: 98c302d5ca71391ecf09cf46a81b821fefe027e4a093493f8cc06ea520af16d987c16a37fb4324fd65389940e6957425adc077917dbee6aee8423090eb29133b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
